// ==UserScript==
// @name Addostream
// @version 1.59.7
// @author Nomo
// @description 두스트림에 기능을 추가한다.
// @supportURL https://github.com/nomomo/Addostream/issues
// @namespace Addostream
// @include *.dostream.com/*
// @include *insagirl-toto.appspot.com/hrm/*
// @include *player.twitch.tv/*
// @include https://chzzk.naver.com/*?embed
// @exclude *insagirl-toto.appspot.com/hrm/notfound.html
// @icon https://raw.githubusercontent.com/nomomo/Addostream/master/images/logo.png
// @homepageURL https://nomomo.github.io/Addostream/
// @downloadURL https://raw.githubusercontent.com/nomomo/Addostream/master/Addostream.user.js
// @updateURL https://raw.githubusercontent.com/nomomo/Addostream/master/Addostream.user.js
// @run-at document-start
// @require https://greasemonkey.github.io/gm4-polyfill/gm4-polyfill.js
// @require https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js
// @require https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js
// @require https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js
// @require https://embed.twitch.tv/embed/v1.js
// @grant GM.addStyle
// @grant GM_addStyle
// @grant GM.getValue
// @grant GM_getValue
// @grant GM.setValue
// @grant GM_setValue
// @grant GM.deleteValue
// @grant GM_deleteValue
// @grant GM.listValues
// @grant GM_listValues
// @grant GM.info
// @grant GM_info
// @grant GM.xmlHttpRequest
// @grant GM_xmlhttpRequest
// @grant GM.registerMenuCommand
// @grant GM_registerMenuCommand
// @grant GM.notification
// @grant GM_notification
// @grant GM.addValueChangeListener
// @grant GM_addValueChangeListener
// @grant GM.removeValueChangeListener
// @grant GM_removeValueChangeListener
// @grant unsafeWindow
// @connect *
// ==/UserScript==
